- name: Home
  link: /
- name: SOBRE
  link: /about/
- name: RESUME
  link: /resume_pt/
- name: GITHUB
  link: https://github.com/leonardosetti
- name: LINKEDIN
  link: https://br.linkedin.com/in/leonardo-setti
  